name: 'Steam deploy'
author: Nikolay Kharitonov <o4kapuk@o4kapuk.ru>
description: 'Deploy games to Steam with Steamworks SDK'
inputs:
  username:
    required: true
    default: ''
    description: 'The username of your builder account.'
  password:
    required: true
    default: ''
    description: 'The password of your builder account.'
  configVdf:
    required: true
    description: 'The contents of STEAM_HOME/config/config.vdf.'
  ssfnFileName:
    required: true
    description: 'The basename of the STEAM_HOME/ssfn file.'
  ssfnFileContents:
    required: true
    description: 'The contents of the file at STEAM_HOME/ssfnFileName.'
  appId:
    required: true
    default: ''
    description: 'The app id within steam partner network.'
  buildDescription:
    required: false
    description: 'Description for this build.'
  rootPath:
    required: true
    description: 'The root path to your builds. This is the base of which depots will search your files.'
  depot1Path:
    required: false
    description: 'The path to depot1.'
  depot2Path:
    required: false
    description: 'The path to depot2.'
  depot3Path:
    required: false
    description: 'The path to depot3.'
  depot4Path:
    required: false
    description: 'The path to depot4.'
  depot5Path:
    required: false
    description: 'The path to depot5.'
  depot6Path:
    required: false
    description: 'The path to depot6.'
  depot7Path:
    required: false
    description: 'The path to depot7.'
  depot8Path:
    required: false
    description: 'The path to depot8.'
  depot9Path:
    required: false
    description: 'The path to depot9.'
  releaseBranch:
    required: false
    description: 'The branch within steam that this build will be automatically put live on.'
outputs:
  manifest:
    description: "The path to the generated manifest.vdf"
runs:
  using: 'node16'
  main: 'dist/index.js'
